### ISSUE TITLE
Remove D-FF from two upstream SFPs. Add mux to allow either direct or via D-FF on third

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc072#18]
The three upstream SFPs can each be connected to a different timing source. Hence return data can't be clocked from same clock.

However, would still like to preserve the ability to have clocking path go direct from clock gen , rather than via FPGA

--> 
1. On two SFPs Remove D-FF (driven by the single board PLL) registering the data going from FPGA to SFP Tx
2. On third (primary) SFP, add a 1:2 fanout and 2:1 Mux with straight through in one arm and via D-FF in the other. Use, for example 854S01 as LVDS Mux

**Comment by DavidCussans** [comment]
Pete,

Yes, the “issue” doesn’t give much detail.

On two upstream channels remove the D-FF on SFP 0,1 and connect the FPGA directly to the SFP Tx pins:

U8 should be removed and UPSTREAM_DATA_{P,N}(0) connected directly to SFP_TD_{P,N}(0) via C106/C100

U3 should be removed and UPSTREAM_DATA_{P,N}(1) connected directly to SFP_TD_{P,N}(1) via C101/C98


On the third upstream channel it should be possible to switch between direct connect to the FPGA and connection via a D-FF:

SFP_TD_{P,N}(2) should be disconnected from U2 and instead connected to the output of multiplexer IC8 ( 854S01 )

One input of IC8 should be connected to the output of U2

For the other input of IC8 there are two choices:


  1.  Disconnect one pair of AUXIO signals from J4 and instead connect to U8 ( adding DC-blocking capacitors in series and adding 100-Ohm termination resistor near U8)
  2.  Disconnect UPSTREAM_DATA_{P,N}(2) from U2 and connect to the input of a 1:2 LVDS fanout ( Use a SY58608 like IC2 etc. ). One output of the newly added 1:2 fanout should go to the input of U2. The other output should go directly to the second input of U8

I don’t have a preference for which option is chosen ( 1. or 2. ). Go with the lowest staff cost one. Probably option 1. I guess.

Cheers!
   David

**Comment by oxfpete** [comment]
Think it is almost done, need your eyes to look at schematic.

**Comment by DavidCussans** [comment]
Schematic change looks good.
Need to double-check that it is OK to connect the "direct out" signal to B16_L14_P/N

**Comment by DavidCussans** [comment]
Need to check that direct output is on suitable FPGA pins.

**Comment by DavidCussans** [comment]
Both clocked and direct output data pins are on same bank (16)

Outputs are on the same bank as input

**Comment by DavidCussans** [comment]
Closed after review
