### ISSUE TITLE
Allow AVR programming cable to override RESET line from uTCA backplane

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc072#19]
When MIB unplugged from backplane RESET line is asserted. This prevents correct programing of MMC uController (ATMEGA128) via JTAG.

---> Add circuitry that allows programming cable to override RESET line

Suggested:
1. Put 0.1 inch header between input of U15 and GND, to allow a link to de-assert RESET*
2. Add a connection from pin-6 ( RESET* line of ATMEL programming header) to output of U15 ( to allow programming header to pull RESET* low. Add a zero ohm link in this path, because David isn't entirely sure of what he is doing...

**Comment by oxfpete** [comment]
Done.

**Comment by DavidCussans** [comment]
Schematic looks good.

**Comment by DavidCussans** [comment]
PL1 needs to move. The space between the two mounting holes is taken up with a solid block of plastic that stabilized the joint between the main PCB and the tongue-2 PCB

**Comment by oxfpete** [comment]
PL1 moved closer to C58

**Comment by oxfpete** [comment]
PL1 well away from C58 and original position, above SK1 and clear of Trenz module

**Comment by DavidCussans** [comment]
Looks Good To Me

Dr David Cussans                    University of Bristol,
office: +44-(117)-95 46879   H.H. Wills Physics Laboratory,
     lab: +44-(117)-33 17199   Tyndall Avenue,
     fax: +44-(117)-925 5624   Bristol BS8 1TL, UK
________________________________

**Comment by DavidCussans** [comment]
Problem spotted - this allows us to program on bench,
but Stoyan points out that this won't allow us to program in crate - since MCH will apply reset at intervals

Conclusion - Pass for pre-production. Continue investigation
