### ISSUE TITLE
Replace 0.1-inch header for MMC uController programming with 0.05-inch header (to match modern cables)

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc072#20]
Replace 0.1-inch header for MMC programming (J13)  with 0.05-inch header (to match modern cables)

**Comment by oxfpete** [comment]
Samtec SHF-105-01-L-D-SM in place of 0.1" connector. Done.

**Comment by DavidCussans** [comment]
Looks good.

**Comment by DavidCussans** [comment]
PCB looks good
