### ISSUE TITLE
Replace DNF resistors R81,R83 with 100nF capacitors

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc072#23]
The current sense resistors in 2.5V , 3.3V lines seem to prevent PTH08T210WAD from operating if voltage is sensed from far side of resistor.
Want accurate voltage regulation
Replace DNF resistors R81,R83 with 100nF capacitors. This seems to solve the issue.

Experiment with also replacing R69,R84 with 1-Ohm resistors

**Comment by oxfpete** [comment]
R81/R83 replace with 100nF - done

**Comment by oxfpete** [comment]
R69/R84 now 1 Ohm 0603 resistors

**Comment by DavidCussans** [comment]
Schematic looks good.
