### ISSUE TITLE
Replace board-sense diode (D12) with Schottky version. Move R102 so that diode can be completely decoupled from MMC uController

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc072#25]
NAT PSU is not supplying 3.3V management power to MIB.

We suspect that the board sense circuit ( the diode between AMC_N-PS0 and AMC_N-PS1 ) isn't functioning correctly. The AFC design (that does work) has a schottky diode directly across AMC_N-PS0 and AMC_N-PS1 , and doesn't have the extra connections to the MMC uController that the MIB ( derived from CERN MMC design ) does.

--> Mimic AFC design. Replace PIN diode D12 in MIB design with Schottky and add ability to disconnect diode , AMC_N-PS0 and AMC_N-PS1 from the rest of the circuitry (using DNF links).

1. Replace R103 with DNF link
2. Add DNF link between BP.AMC_N-PS<1>
3. Replace D12 with SS16 Schottky diode.

Suggest using SS16 as a replacement ( see AFC schematics, D2 of https://edms.cern.ch/ui/file/3060691/1/documentation_Schematic_Print_AFCv4.0.2_FMC-1.PDF )

**Comment by oxfpete** [comment]
point 1 - done

**Comment by oxfpete** [comment]
point 3 - done
point 2 - not done yet

**Comment by oxfpete** [comment]
I am unable to view the cern link sadly, possible to send a screenshot by email? I will place a DNF link where I think it is meant to be to complete point 2 but I will not say this item is complete yet.

**Comment by DavidCussans** [comment]
Schematic looks good.

**Comment by DavidCussans** [comment]
PCB looks good. Diode seems to be available.
