### ISSUE TITLE
PRESENCE_12V line ( currently connected to PA1 ) should be connected to PF0 .

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc072#36]
PRESENCE_12V line ( currently connected to PA1 , which is a digital-only line ) should be connected to PF0 instead ( which can function as an ADC )

**Comment by oxfpete** [comment]
Done and done.

**Comment by DavidCussans** [comment]
Needs a correction:
DCDC_3V3_PG has been connected to PF0 , *not* PRESENCE_12V

**Comment by DavidCussans** [comment]
Updated schematic looks good.

**Comment by DavidCussans** [comment]
Patched MMC works in Bristol.
