### ISSUE TITLE
Move  blue LED to correct position to follow uTCA standard.

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc072#44]
Blue LED should be on the underside of the board near the front ( i.e. near the extraction handle)

Images taken from AFC design using Altium Designer: 
 
(Looking at the board it seems that the LED would be better aligned with light pipe if about 0.5mm higher ( further away from the bottom of the board)

<img width="1360" alt="afc_blue_led_footprint_dimensions" src="https://github.com/user-attachments/assets/3e5663cf-6818-4c5a-98c6-250163a40a85">
<img width="1360" alt="afc_blue_led_delta_to_mh1_3d" src="https://github.com/user-attachments/assets/859bf72b-99dd-47a9-af2a-d844fa7d1ce1">
<img width="1360" alt="afc_blue_led_delta_to_mh1_zoom" src="https://github.com/user-attachments/assets/12ca9d7b-fdcc-4e8c-895e-896952bf6baa">

Photograph of AFC in crate with blue LED illuminated:
![IMG_20240723_113950109](https://github.com/user-attachments/assets/e9699efb-0e88-494d-b114-a787c89a9867)

Another photo of AFC:
![IMG_20240723_132314960_HDR](https://github.com/user-attachments/assets/1bbd4da5-580c-4005-a9f9-e0ca0935e7cf)

**Comment by oxfpete** [comment]
I don't think the new position is correct at all on the layout I have just submitted. Is that mounting point on the PCB I have?

**Comment by DavidCussans** [comment]
The blue LED is in roughly the right place - on the bottom near the front of the board - but needs tweaking.

The image at https://github.com/user-attachments/assets/12ca9d7b-fdcc-4e8c-895e-896952bf6baa shows the position relative to MH6 on the DUNE MIB. ( There are other holes on the AFC which are used to mount the FMCs but these aren't present on the MIB ).

In its new position LED also needs to be a "side launch" (like on the FIB ) to type to shine the light horizontally (rather than a vertical mount )

Dr David Cussans                    University of Bristol,
office: +44-(117)-95 46879   H.H. Wills Physics Laboratory,
     lab: +44-(117)-33 17199   Tyndall Avenue,
     fax: +44-(117)-925 5624   Bristol BS8 1TL, UK

________________________________

**Comment by DavidCussans** [comment]
Blue LED , DS1 still needs to be moved.

**Comment by oxfpete** [comment]
Done

**Comment by DavidCussans** [comment]
Checked on mib_rev3ox_v223.

Looks Good To Me
