### ISSUE TITLE
Move red and green LEDs to "standard" positions for Schroff/nvent front panel mechanism. Remove existing light-pipe and rely on front panel mechanism

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc072#47]
Schroff/nVent front panel mechanism includes light pipes for the two auxilliary LEDs ( red / green )
( https://schroff.nvent.com/en-gb/products/enc20849-153 )

--> Remove existing light-pipe (U1)

--> Move Red and Green LEDs to correct positions to suit nVent light pipe
( https://schroff.nvent.com/sites/g/files/hdkjer281/files/acquiadam_assets/2021-06/70849-045.pdf )
... the Blue LED has already been moved in issue #44 
N.B.
1. Can probably measure positions from AFC
2. The LED nearest front of board should be replaced with an "edge launch" . The one furthest away should stay as vertical launch.
3. The edge launch LED (shining out of the crate) is on the top surface. The vertical (perpendicular to the board into light pipe) LED is on the bottom surface.
4.

**Comment by DavidCussans** [comment]
mob_rev3ox_v221.brd looks like LED positions incorrect.

on LED D1 with respect to mounting hole: delta-x = 6.97mm , delta-y = 1.1mm ,

looking at AFC design it looks like this should be delta-x = 5.583mm , delta-y = 1.069mm . i.e. y position OK within tolerance, x position needs to be shifted by ~ 1.4mm

Screenshot from Altium: ![Screenshot 2024-08-28 111439](https://github.com/user-attachments/assets/2095511c-f04b-447b-883b-d12a114feaf5)

**Comment by oxfpete** [comment]
LED D1 moved.

**Comment by DavidCussans** [comment]
Closing since
1. Checked by DGC
2. WOn't stop the board working
