### ISSUE TITLE
Swap pins 1,3,5 of J4 from GND to VCC3v3 ( to allow powering of LEDs on daughter board)

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc072#54]
There are no LEDs to indicate the status of the upstream links on the MIB.

Add +3.3V power to allow LEDs on daughterboard to be powered from main board.

Swap pins 1,3,5 of J4 from GND to vcc3v3 

The attached screenshot shows which pins:
![Screenshot 2024-08-28 124021](https://github.com/user-attachments/assets/43625232-e465-4749-9cce-1824dd3f4aad)

**Comment by oxfpete** [comment]
Done.

**Comment by DavidCussans** [comment]
Closed on review
